### ISSUE TITLE
Support for helmt --set-file feature

### ISSUE THREAD

**Issue by vivian-src** [syncier/helmt#15]
### What problem are you trying to solve?
I would like to pass the root certificate file to helmt (example helm template --set-file values=ca.crt) so as to avoid exposing the certificate in the values.yaml file in the git repo.

### How should the problem be solved?
We'd like an option in helmt to set values as files(example helmt --set-file globalCert=ca.crt).
 
### Any alternatives you've considered?
current alternative is create the values.yaml with cert value set and use helmt to generate manifest. Then delete the values.yaml file before commiting to the git repo

**Comment by torstenwalter** [comment]
@vivian-src The best alternative I see is to have a second value file with secrets e.g a values-secret.yaml with the ca.crt. That way you could still version control the `values.yaml` and `helm-chart.yaml` would reference both values files.
This way you also notice that something is missing to render the resources.

The idea behind helmt was more to have everything in version control. So if you need secrets it's preferred to provision those separately and then reference those existing secret.

**Comment by vivian-src** [comment]
@torstenwalter Makes sense and thus this issue can be closed
